export const APP_ICONS = {
    notifications: 'tdesign:notification',
    logout: 'clarity:logout-line',
    settings: 'ep:setting',
    user: 'mdi:people-outline',
    question: 'ph:question',
    plus: 'tabler:plus',
    search: 'teenyicons:search-outline',
    youtube: 'logos:youtube-icon',
    instagram: 'skill-icons:instagram',
    facebook: 'logos:facebook',
    checkList: 'solar:list-check-broken',
    clock: 'ph:clock',
    tag: 'mdi:tag-outline',
    check: 'ic:round-check',
    next: 'ooui:next-ltr',
    dashboard: 'ic:round-dashboard',
    order: 'material-symbols:order-approve-outline',
    inventory: 'ic:outline-inventory-2',
    billing: 'solar:bill-list-linear',
    orders:'material-symbols:orders-outline-rounded',
    reports: 'mingcute:inventory-line'
}